typography_spectrum: 0.08110389020293951
color:
  brandStrength: 0.39530387055128813
  lightness: 0.17655174271203578
  saturation: 0.2004912793636322
  rhythmicContrast: 0.7972703566774726
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.5595175784546882
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4136f9d0-e247-433b-b977-afc7c09f3df5.jpg
name: The Morton Group
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7da0fe64-8d9a-4e82-8d1b-a551787ae38f.png
title: Welcome to YOUCentered Real Estate
description: |
  Everything we do is focused on YOU
